### PR TITLE
add both versions of logo

### PR DESCRIPTION
**Pull request by risograph**
both exports are in **brand white by default**. this shouldnt be an issue considering **they are `.svg`s**. if you need to change the color then **create a separate file with the color changes**.

### CODE REVIEW

**Comment by risograph** [comment]
brand white being `#FFFAE9` or `rgba(255, 250, 233, 1)` maybe we should call it non-biased white?

**Comment by risograph** [comment]
forgot to add the nbo logos. added.

**Review by TheAwesome98-Real — APPROVED** [review]
ok cool

**Comment by TheAwesome98-Real** [comment]
wait shit did i just approve the entire thing i thought it needed everyone to

**Comment by Quantum-Codes** [comment]
Nice. I'm deleting the branch

**Pull request merged**
